export interface ServiceTemplate {
  nameAr: string;
  price: number;
  duration: number;
  category: string;
  description: string;
  icon: string;
  color: string;
  active: boolean;
  status: 'active';
}

export interface CategoryInfo {
  key: string;
  icon: string;
  color: string;
  bgColor: string;
  textColor: string;
  label: string;
}

export const CATEGORIES: CategoryInfo[] = [
  {
    key: 'الإسعافات الأولية',
    icon: '🩹',
    color: 'red',
    bgColor: 'bg-red-100',
    textColor: 'text-red-700',
    label: 'الإسعافات الأولية',
  },
  {
    key: 'الحقن والأدوية',
    icon: '💉',
    color: 'blue',
    bgColor: 'bg-blue-100',
    textColor: 'text-blue-700',
    label: 'الحقن والأدوية',
  },
  {
    key: 'العلامات الحيوية',
    icon: '🫀',
    color: 'pink',
    bgColor: 'bg-pink-100',
    textColor: 'text-pink-700',
    label: 'العلامات الحيوية',
  },
  {
    key: 'الحروق والجروح',
    icon: '🩺',
    color: 'orange',
    bgColor: 'bg-orange-100',
    textColor: 'text-orange-700',
    label: 'الحروق والجروح',
  },
  {
    key: 'الكسور والإصابات',
    icon: '🦴',
    color: 'amber',
    bgColor: 'bg-amber-100',
    textColor: 'text-amber-700',
    label: 'الكسور والإصابات',
  },
  {
    key: 'التنفس والأكسجين',
    icon: '🫁',
    color: 'cyan',
    bgColor: 'bg-cyan-100',
    textColor: 'text-cyan-700',
    label: 'التنفس والأكسجين',
  },
  {
    key: 'الطوارئ',
    icon: '🚑',
    color: 'rose',
    bgColor: 'bg-rose-100',
    textColor: 'text-rose-700',
    label: 'الطوارئ',
  },
  {
    key: 'الفحوصات السريعة',
    icon: '🔬',
    color: 'violet',
    bgColor: 'bg-violet-100',
    textColor: 'text-violet-700',
    label: 'الفحوصات السريعة',
  },
  {
    key: 'الخدمات المنزلية',
    icon: '🏠',
    color: 'emerald',
    bgColor: 'bg-emerald-100',
    textColor: 'text-emerald-700',
    label: 'الخدمات المنزلية',
  },
  {
    key: 'رعاية الأطفال',
    icon: '👶',
    color: 'sky',
    bgColor: 'bg-sky-100',
    textColor: 'text-sky-700',
    label: 'رعاية الأطفال',
  },
  {
    key: 'رعاية كبار السن',
    icon: '🧓',
    color: 'teal',
    bgColor: 'bg-teal-100',
    textColor: 'text-teal-700',
    label: 'رعاية كبار السن',
  },
  {
    key: 'متابعة العلاج',
    icon: '📋',
    color: 'indigo',
    bgColor: 'bg-indigo-100',
    textColor: 'text-indigo-700',
    label: 'متابعة العلاج',
  },
  {
    key: 'المحاليل الوريدية',
    icon: '💉',
    color: 'lime',
    bgColor: 'bg-lime-100',
    textColor: 'text-lime-700',
    label: 'المحاليل الوريدية',
  },
  {
    key: 'المضادات الحيوية',
    icon: '💊',
    color: 'fuchsia',
    bgColor: 'bg-fuchsia-100',
    textColor: 'text-fuchsia-700',
    label: 'المضادات الحيوية',
  },
  {
    key: 'المهدئات والألم',
    icon: '😴',
    color: 'slate',
    bgColor: 'bg-slate-100',
    textColor: 'text-slate-700',
    label: 'المهدئات والألم',
  },
  {
    key: 'الفيتامينات والمكملات',
    icon: '🌟',
    color: 'yellow',
    bgColor: 'bg-yellow-100',
    textColor: 'text-yellow-700',
    label: 'الفيتامينات والمكملات',
  },
];

export const DEFAULT_SERVICES: ServiceTemplate[] = [
  // ═══════════════════════════════════════════════════════════
  // 1. الإسعافات الأولية (First Aid) - 10 services
  // ═══════════════════════════════════════════════════════════
  {
    nameAr: 'تنظيف وتطهير الجروح',
    price: 500,
    duration: 15,
    category: 'الإسعافات الأولية',
    description: 'تنظيف الجروح بمحلول معقم وتطهيرها لمنع العدوى',
    icon: '🩹',
    color: 'red',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'إزالة جسم غريب',
    price: 800,
    duration: 20,
    category: 'الإسعافات الأولية',
    description: 'إزالة الأجسام الغريبة من الجلد أو الأنسجة السطحية بأمان',
    icon: '🔧',
    color: 'red',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'إيقاف النزيف الخفيف',
    price: 600,
    duration: 15,
    category: 'الإسعافات الأولية',
    description: 'إيقاف النزيف السطحي والخفيف بالضغط والضمادات المناسبة',
    icon: '🩸',
    color: 'red',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'ضماد وإراحة العضلات',
    price: 400,
    duration: 15,
    category: 'الإسعافات الأولية',
    description: 'وضع ضمادات مرنة لدعم العضلات والمفاصل المصابة',
    icon: '🩹',
    color: 'red',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'علاج الدوخة والإغماء',
    price: 700,
    duration: 20,
    category: 'الإسعافات الأولية',
    description: 'إسعاف حالات الدوخة والإغماء ومراقبة حالة المريض',
    icon: '😵',
    color: 'red',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'إسعاف الحساسية الموسمية',
    price: 600,
    duration: 15,
    category: 'الإسعافات الأولية',
    description: 'علاج أعراض الحساسية الموسمية والتهابات الأنف والعين',
    icon: '🤧',
    color: 'red',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'علاج لسعات الحشرات',
    price: 500,
    duration: 15,
    category: 'الإسعافات الأولية',
    description: 'إسعاف لسعات الحشرات والنمل والنحل وتخفيف التورم',
    icon: '🐝',
    color: 'red',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'علاج عضة حيوان',
    price: 1000,
    duration: 25,
    category: 'الإسعافات الأولية',
    description: 'تنظيف عضة الحيوان وتطهيرها وإعطاء التطعيم اللازم',
    icon: '🐕',
    color: 'red',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'إسعاف التسمم الغذائي الخفيف',
    price: 900,
    duration: 30,
    category: 'الإسعافات الأولية',
    description: 'علاج أعراض التسمم الغذائي البسيطة وإعادة الترطيب',
    icon: '🤢',
    color: 'red',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'إسعاف الصدمة العصبية',
    price: 1200,
    duration: 30,
    category: 'الإسعافات الأولية',
    description: 'تهدئة المريض وتقديم الإسعافات الأولية للصدمة العصبية',
    icon: '😰',
    color: 'red',
    active: true,
    status: 'active',
  },

  // ═══════════════════════════════════════════════════════════
  // 2. الحقن والأدوية (Injections & Medications) - 10 services
  // ═══════════════════════════════════════════════════════════
  {
    nameAr: 'حقنة مضاد حيوي',
    price: 1500,
    duration: 15,
    category: 'الحقن والأدوية',
    description: 'حقن مضاد حيوي عضلية أو وريدية حسب وصفة الطبيب',
    icon: '💉',
    color: 'blue',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'حقنة مسكنة للألم',
    price: 800,
    duration: 10,
    category: 'الحقن والأدوية',
    description: 'حقن مسكنة للألم الخفيف إلى المتوسط عضلية أو وريدية',
    icon: '💊',
    color: 'blue',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'حقنة مضاد للالتهاب',
    price: 1200,
    duration: 15,
    category: 'الحقن والأدوية',
    description: 'حقن كورتيزون أو مضاد التهاب غير ستيرويدي',
    icon: '💉',
    color: 'blue',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'محلول مغذي وريدي',
    price: 2000,
    duration: 45,
    category: 'الحقن والأدوية',
    description: 'محلول ملح أو جلوكوز وريدي لمعالجة الجفاف ونقص السوائل',
    icon: '🩺',
    color: 'blue',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'حقنة مضاد للحساسية',
    price: 1000,
    duration: 15,
    category: 'الحقن والأدوية',
    description: 'حقن مضاد الهيستامين لعلاج ردود الفعل التحسسية',
    icon: '💉',
    color: 'blue',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'حقنة فيتامين د',
    price: 1800,
    duration: 10,
    category: 'الحقن والأدوية',
    description: 'حقن فيتامين د عضلية لعلاج النقص الحاد',
    icon: '☀️',
    color: 'blue',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'حقنة حديد وريدية',
    price: 2500,
    duration: 30,
    category: 'الحقن والأدوية',
    description: 'حقن الحديد وريدياً لعلاج فقر الدم الشديد',
    icon: '🩸',
    color: 'blue',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'تطعيم الكزاز',
    price: 1200,
    duration: 10,
    category: 'الحقن والأدوية',
    description: 'حقنة تطعيم ضد الكزاز للجروح والإصابات',
    icon: '💉',
    color: 'blue',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'حقنة مضاد للقيء',
    price: 700,
    duration: 10,
    category: 'الحقن والأدوية',
    description: 'حقنة لوقف القيء والغثيان الشديد',
    icon: '💊',
    color: 'blue',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'صرف وصفة طبية',
    price: 500,
    duration: 10,
    category: 'الحقن والأدوية',
    description: 'صرف الأدوية حسب الوصفة الطبية مع شرح الاستخدام',
    icon: '📋',
    color: 'blue',
    active: true,
    status: 'active',
  },

  // ═══════════════════════════════════════════════════════════
  // 3. العلامات الحيوية (Vital Signs) - 8 services
  // ═══════════════════════════════════════════════════════════
  {
    nameAr: 'قياس ضغط الدم',
    price: 300,
    duration: 10,
    category: 'العلامات الحيوية',
    description: 'قياس ضغط الدم الانقباضي والانبساطي بجهاز دقيق',
    icon: '💓',
    color: 'pink',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'قياس النبض',
    price: 200,
    duration: 5,
    category: 'العلامات الحيوية',
    description: 'قياس معدل ضربات القلب وانتظام النبض',
    icon: '❤️',
    color: 'pink',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'قياس درجة الحرارة',
    price: 200,
    duration: 5,
    category: 'العلامات الحيوية',
    description: 'قياس درجة حرارة الجسم بميزان حراري رقمي دقيق',
    icon: '🌡️',
    color: 'pink',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'قياس مستوى الأكسجين',
    price: 300,
    duration: 5,
    category: 'العلامات الحيوية',
    description: 'قياس تشبع الدم بالأكسجين بجهاز نبض الأكسجين',
    icon: '🫁',
    color: 'pink',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'قياس السكر التراكمي',
    price: 800,
    duration: 10,
    category: 'العلامات الحيوية',
    description: 'فحص مستوى السكر التراكمي في الدم لمتابعة مرضى السكري',
    icon: '🩸',
    color: 'pink',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'فحص السكر العشوائي',
    price: 400,
    duration: 5,
    category: 'العلامات الحيوية',
    description: 'قياس سكر الدم العشوائي بجهاز فحص سريع',
    icon: '🍬',
    color: 'pink',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'تخطيط القلب السريع',
    price: 1500,
    duration: 15,
    category: 'العلامات الحيوية',
    description: 'تخطيط كهربائية القلب لفحص نظم القلب واكتشاف المشاكل',
    icon: '📈',
    color: 'pink',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'قياس معدل التنفس',
    price: 200,
    duration: 5,
    category: 'العلامات الحيوية',
    description: 'مراقبة معدل التنفس وعمقه لتقييم الوظيفة التنفسية',
    icon: '🌬️',
    color: 'pink',
    active: true,
    status: 'active',
  },

  // ═══════════════════════════════════════════════════════════
  // 4. الحروق والجروح (Burns & Wounds) - 10 services
  // ═══════════════════════════════════════════════════════════
  {
    nameAr: 'علاج الحروق من الدرجة الأولى',
    price: 800,
    duration: 20,
    category: 'الحروق والجروح',
    description: 'علاج الحروق السطحية الخفيفة بالمراهم والضمادات المبردة',
    icon: '🔥',
    color: 'orange',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'علاج الحروق من الدرجة الثانية',
    price: 1500,
    duration: 30,
    category: 'الحروق والجروح',
    description: 'علاج الحروق المتوسطة مع فقاعات وتطهير وضماد متخصص',
    icon: '🔥',
    color: 'orange',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'علاج الجروح المفتوحة',
    price: 1200,
    duration: 25,
    category: 'الحروق والجروح',
    description: 'تنظيف وتطهير الجروح المفتوحة ووضع ضمادات معقمة',
    icon: '🩹',
    color: 'orange',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'خياطة الجروح',
    price: 2000,
    duration: 30,
    category: 'الحروق والجروح',
    description: 'خياطة الجروح العميقة بخيوط طبية مع تخدير موضعي',
    icon: '🪡',
    color: 'orange',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'إزالة الغرز',
    price: 400,
    duration: 10,
    category: 'الحروق والجروح',
    description: 'إزالة الغرز الطبية بعد التئام الجرح',
    icon: '✂️',
    color: 'orange',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'علاج الجروح المتقيحة',
    price: 1500,
    duration: 25,
    category: 'الحروق والجروح',
    description: 'تنظيف الجروح الملتهبة والمتقيحة وصرف المادة القيحية',
    icon: '🦠',
    color: 'orange',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'تغيير الضمادات',
    price: 300,
    duration: 10,
    category: 'الحروق والجروح',
    description: 'تغيير الضمادات القديمة وتطهير الجرح ووضع ضمادات جديدة',
    icon: '🩹',
    color: 'orange',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'علاج الحروق الكيميائية الخفيفة',
    price: 1800,
    duration: 30,
    category: 'الحروق والجروح',
    description: 'غسل وتطهير الحروق الناتجة عن المواد الكيميائية',
    icon: '⚗️',
    color: 'orange',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'علاج جرح الحلاقة والقطع',
    price: 700,
    duration: 15,
    category: 'الحروق والجروح',
    description: 'إسعاف القطوع السطحية والحلاق وإيقاف النزيف',
    icon: '🔪',
    color: 'orange',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'ضماد الحروق المتخصص',
    price: 1000,
    duration: 20,
    category: 'الحروق والجروح',
    description: 'وضع ضمادات حروق متخصصة مغطاة بالجل المائي',
    icon: '🧴',
    color: 'orange',
    active: true,
    status: 'active',
  },

  // ═══════════════════════════════════════════════════════════
  // 5. الكسور والإصابات (Fractures & Injuries) - 8 services
  // ═══════════════════════════════════════════════════════════
  {
    nameAr: 'تجبير الكسور البسيطة',
    price: 2000,
    duration: 30,
    category: 'الكسور والإصابات',
    description: 'تثبيت الكسور البسيطة بجبيرة جبسية أو بلاستيكية',
    icon: '🦴',
    color: 'amber',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'علاج الالتواءات',
    price: 1000,
    duration: 20,
    category: 'الكسور والإصابات',
    description: 'علاج التواءات المفاصل بالضمادات والراحة الباردة',
    icon: '💪',
    color: 'amber',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'علاج الشد العضلي',
    price: 800,
    duration: 15,
    category: 'الكسور والإصابات',
    description: 'علاج شد العضلات بالكمادات والمسكنات الموضعية',
    icon: '🦵',
    color: 'amber',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'تثبيت خلع المفصل',
    price: 2500,
    duration: 30,
    category: 'الكسور والإصابات',
    description: 'إعادة المفصل الخلوع لموضعه الطبيعي وتثبيته',
    icon: '🦴',
    color: 'amber',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'تصوير شعاعي أولي',
    price: 1500,
    duration: 15,
    category: 'الكسور والإصابات',
    description: 'أشعة سينية سريعة للكشف عن الكسور والإصابات العظمية',
    icon: '☢️',
    color: 'amber',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'علاج إصابة الظهر',
    price: 1200,
    duration: 25,
    category: 'الكسور والإصابات',
    description: 'علاج آلام الظهر الخفيفة والإصابات العضلية',
    icon: '🔙',
    color: 'amber',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'علاج إصابة الرقبة',
    price: 1200,
    duration: 20,
    category: 'الكسور والإصابات',
    description: 'علاج آلام الرقبة وتمدد العضلات بطوق الرقبة',
    icon: '🦴',
    color: 'amber',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'إزالة الجبيرة',
    price: 500,
    duration: 15,
    category: 'الكسور والإصابات',
    description: 'إزالة الجبيرة بعد التئام الكسر وتقييم حالة العظم',
    icon: '🛠️',
    color: 'amber',
    active: true,
    status: 'active',
  },

  // ═══════════════════════════════════════════════════════════
  // 6. التنفس والأكسجين (Respiratory & Oxygen) - 8 services
  // ═══════════════════════════════════════════════════════════
  {
    nameAr: 'العلاج بالأكسجين',
    price: 1500,
    duration: 30,
    category: 'التنفس والأكسجين',
    description: 'إعطاء الأكسجين عبر القناع أو الأنبوب الأنفي لتحسين التنفس',
    icon: '🫁',
    color: 'cyan',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'علاج الربو المستمر',
    price: 1200,
    duration: 20,
    category: 'التنفس والأكسجين',
    description: 'علاج نوبات الربو بالبخاخات والأدوية الموسعة للشعب',
    icon: '💨',
    color: 'cyan',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'علاج ضيق التنفس',
    price: 1000,
    duration: 20,
    category: 'التنفس والأكسجين',
    description: 'تقييم وعلاج ضيق التنفس الحاد بالأدوية والأكسجين',
    icon: '😮‍💨',
    color: 'cyan',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'استنشاق محلول ملحي',
    price: 600,
    duration: 20,
    category: 'التنفس والأكسجين',
    description: 'علاج بالاستنشاق عبر جهاز النيبولايزر لتوسيع الشعب',
    icon: '💧',
    color: 'cyan',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'شفط الإفرازات',
    price: 800,
    duration: 15,
    category: 'التنفس والأكسجين',
    description: 'شفط الإفرازات والمخاط من المجاري التنفسية',
    icon: '🫁',
    color: 'cyan',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'علاج السعال الشديد',
    price: 600,
    duration: 15,
    category: 'التنفس والأكسجين',
    description: 'علاج السعال المستمر بالأدوية المناسبة والاستنشاق',
    icon: '🤧',
    color: 'cyan',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'قياس وظائف التنفس',
    price: 1000,
    duration: 20,
    category: 'التنفس والأكسجين',
    description: 'فحص وظائف الرئة بجهاز قياس التنفس لتقييم القدرة التنفسية',
    icon: '📊',
    color: 'cyan',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'علاج الانسداد الأنفي',
    price: 500,
    duration: 10,
    category: 'التنفس والأكسجين',
    description: 'علاج انسداد الأنف والتهاب الجيوب الأنفية بالأدوية الموضعية',
    icon: '👃',
    color: 'cyan',
    active: true,
    status: 'active',
  },

  // ═══════════════════════════════════════════════════════════
  // 7. الطوارئ (Emergency) - 10 services
  // ═══════════════════════════════════════════════════════════
  {
    nameAr: 'إنعاش قلبي رئوي',
    price: 3000,
    duration: 30,
    category: 'الطوارئ',
    description: 'إجراء إنعاش قلبي رئوي فوري لحالات توقف القلب والتنفس',
    icon: '❤️‍🩹',
    color: 'rose',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'علاج الصدمة التحسسية',
    price: 2500,
    duration: 25,
    category: 'الطوارئ',
    description: 'إسعاف الحساسية المفرطة بحقنة الأدرينالين فوراً',
    icon: '⚠️',
    color: 'rose',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'إيقاف النزيف الحاد',
    price: 2000,
    duration: 25,
    category: 'الطوارئ',
    description: 'إيقاف النزيف الشديد بالضغط المباشر وربط الضمادات',
    icon: '🩸',
    color: 'rose',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'إسعاف حادث مروري',
    price: 3500,
    duration: 45,
    category: 'الطوارئ',
    description: 'إسعاف إصابات الحوادث المرورية وتثبيت الكسور والجروح',
    icon: '🚗',
    color: 'rose',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'علاج نوبة القلب المشتبهة',
    price: 4000,
    duration: 30,
    category: 'الطوارئ',
    description: 'إسعاف أولي لنوبة قلبية مشتبهة وتنظيم النقل للمستشفى',
    icon: '🫀',
    color: 'rose',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'إسعاف التسمم الحاد',
    price: 3000,
    duration: 40,
    category: 'الطوارئ',
    description: 'علاج التسمم الحاد بغسل المعدة وإعطاء الترياق المناسب',
    icon: '☠️',
    color: 'rose',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'علاج نوبة الصرع',
    price: 2000,
    duration: 25,
    category: 'الطوارئ',
    description: 'إسعاف نوبة الصرع وحماية المريض من الإصابة أثناء النوبة',
    icon: '⚡',
    color: 'rose',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'إسعاف الغرق',
    price: 3000,
    duration: 35,
    category: 'الطوارئ',
    description: 'إسعاف حالات الغرق وإعادة التنفس والعناية بالرئتين',
    icon: '🌊',
    color: 'rose',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'علاج الحروق الشديدة',
    price: 3500,
    duration: 40,
    category: 'الطوارئ',
    description: 'إسعاف الحروق من الدرجة الثالثة والشديدة وتثبيت الحالة',
    icon: '🔥',
    color: 'rose',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'تنظيم نقل إسعافي',
    price: 5000,
    duration: 20,
    category: 'الطوارئ',
    description: 'تنظيم سيارة إسعاف لنقل المريض إلى المستشفى المناسب',
    icon: '🚑',
    color: 'rose',
    active: true,
    status: 'active',
  },

  // ═══════════════════════════════════════════════════════════
  // 8. الفحوصات السريعة (Quick Examinations) - 10 services
  // ═══════════════════════════════════════════════════════════
  {
    nameAr: 'فحص كوفيد السريع',
    price: 1000,
    duration: 15,
    category: 'الفحوصات السريعة',
    description: 'فحص سريع للكشف عن فيروس كورونا المستجد',
    icon: '🦠',
    color: 'violet',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'فحص الملاريا السريع',
    price: 800,
    duration: 15,
    category: 'الفحوصات السريعة',
    description: 'فحص سريع للكشف عن طفيل الملاريا في الدم',
    icon: '🦟',
    color: 'violet',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'فحص الحمل',
    price: 500,
    duration: 10,
    category: 'الفحوصات السريعة',
    description: 'فحص سريع لتأكيد الحمل بتحليل البول',
    icon: '🤰',
    color: 'violet',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'فحص الدم الشامل',
    price: 1500,
    duration: 15,
    category: 'الفحوصات السريعة',
    description: 'تحليل دم شامل لفحص كريات الدم والهيموغلوبين والصفائح',
    icon: '🩸',
    color: 'violet',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'فحص البول',
    price: 600,
    duration: 10,
    category: 'الفحوصات السريعة',
    description: 'تحليل البول للكشف عن التهابات المسالك البولية',
    icon: '🧪',
    color: 'violet',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'فحص الدنجي',
    price: 1000,
    duration: 15,
    category: 'الفحوصات السريعة',
    description: 'فحص سريع للكشف عن حمى الدنجي',
    icon: '🦟',
    color: 'violet',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'فحص التهاب الكبد',
    price: 1200,
    duration: 15,
    category: 'الفحوصات السريعة',
    description: 'فحص سريع للكشف عن التهاب الكبد الوبائي ب وأنواع أخرى',
    icon: '🫁',
    color: 'violet',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'فحص الكوليرا السريع',
    price: 800,
    duration: 10,
    category: 'الفحوصات السريعة',
    description: 'فحص سريع للكشف عن بكتيريا الكوليرا',
    icon: '🦠',
    color: 'violet',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'فحص التيفوئيد',
    price: 900,
    duration: 15,
    category: 'الفحوصات السريعة',
    description: 'فحص سريع للكشف عن حمى التيفوئيد',
    icon: '🌡️',
    color: 'violet',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'فحص فقر الدم',
    price: 700,
    duration: 10,
    category: 'الفحوصات السريعة',
    description: 'قياس مستوى الهيموغلوبين للكشف عن فقر الدم',
    icon: '🩸',
    color: 'violet',
    active: true,
    status: 'active',
  },

  // ═══════════════════════════════════════════════════════════
  // 9. الخدمات المنزلية (Home Services) - 8 services
  // ═══════════════════════════════════════════════════════════
  {
    nameAr: 'زيارة منزلية عامة',
    price: 3000,
    duration: 45,
    category: 'الخدمات المنزلية',
    description: 'زيارة طبيب إلى المنزل للفحص والتشخيص الأولي',
    icon: '🏠',
    color: 'emerald',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'حقنة منزلية',
    price: 1500,
    duration: 20,
    category: 'الخدمات المنزلية',
    description: 'ممرض لحقن الدواء في المنزل حسب وصفة الطبيب',
    icon: '💉',
    color: 'emerald',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'محلول وريدي منزلي',
    price: 2500,
    duration: 60,
    category: 'الخدمات المنزلية',
    description: 'تركيب محلول وريدي في المنزل لمرضى الجفاف',
    icon: '🩺',
    color: 'emerald',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'تغيير ضمادات منزلي',
    price: 1000,
    duration: 20,
    category: 'الخدمات المنزلية',
    description: 'ممرض لتغيير الضمادات والعناية بالجروح في المنزل',
    icon: '🩹',
    color: 'emerald',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'قياس العلامات الحيوية منزلياً',
    price: 800,
    duration: 15,
    category: 'الخدمات المنزلية',
    description: 'فحص الضغط والسكر والحرارة في المنزل',
    icon: '🫀',
    color: 'emerald',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'علاج طبيعي منزلي',
    price: 2000,
    duration: 45,
    category: 'الخدمات المنزلية',
    description: 'جلسة علاج طبيعي في المنزل لإعادة التأهيل',
    icon: '💪',
    color: 'emerald',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'رعاية مريض طريح الفراش',
    price: 2500,
    duration: 60,
    category: 'الخدمات المنزلية',
    description: 'رعاية شاملة للمريض طريح الفراش في المنزل',
    icon: '🛏️',
    color: 'emerald',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'استشارة طبية عن بُعد',
    price: 1000,
    duration: 20,
    category: 'الخدمات المنزلية',
    description: 'استشارة طبية عبر الهاتف أو الفيديو مع طبيب مختص',
    icon: '📱',
    color: 'emerald',
    active: true,
    status: 'active',
  },

  // ═══════════════════════════════════════════════════════════
  // 10. رعاية الأطفال (Pediatric Care) - 8 services
  // ═══════════════════════════════════════════════════════════
  {
    nameAr: 'فحص الطفل العام',
    price: 800,
    duration: 20,
    category: 'رعاية الأطفال',
    description: 'فحص صحي شامل للطفل وتقييم نموه وتطوره',
    icon: '👶',
    color: 'sky',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'علاج حمى الأطفال',
    price: 600,
    duration: 15,
    category: 'رعاية الأطفال',
    description: 'علاج ارتفاع حرارة الطفل وخفض الحمى بالأدوية المناسبة',
    icon: '🌡️',
    color: 'sky',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'علاج إسهال الأطفال',
    price: 800,
    duration: 20,
    category: 'رعاية الأطفال',
    description: 'علاج الإسهال عند الأطفال ومحلول الإماهة الفموية',
    icon: '🥤',
    color: 'sky',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'علاج سعال الأطفال',
    price: 600,
    duration: 15,
    category: 'رعاية الأطفال',
    description: 'علاج السعال والزكام عند الأطفال بالأدوية الآمنة',
    icon: '🤧',
    color: 'sky',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'تطعيم الأطفال',
    price: 1000,
    duration: 15,
    category: 'رعاية الأطفال',
    description: 'إعطاء التطعيمات الأساسية للأطفال حسب جدول التطعيمات',
    icon: '💉',
    color: 'sky',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'علاج التهاب الأذن',
    price: 800,
    duration: 15,
    category: 'رعاية الأطفال',
    description: 'علاج التهاب الأذن الوسطى الشائع عند الأطفال',
    icon: '👂',
    color: 'sky',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'فحص حديثي الولادة',
    price: 1200,
    duration: 25,
    category: 'رعاية الأطفال',
    description: 'فحص شامل لحديثي الولادة وتقييم الصحة العامة',
    icon: '🍼',
    color: 'sky',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'علاج طفح الحفاضات',
    price: 500,
    duration: 10,
    category: 'رعاية الأطفال',
    description: 'علاج التهاب وطفح الجلد الناتج عن الحفاضات',
    icon: '🧴',
    color: 'sky',
    active: true,
    status: 'active',
  },

  // ═══════════════════════════════════════════════════════════
  // 11. رعاية كبار السن (Elderly Care) - 8 services
  // ═══════════════════════════════════════════════════════════
  {
    nameAr: 'فحص صحة كبار السن',
    price: 1000,
    duration: 25,
    category: 'رعاية كبار السن',
    description: 'فحص صحي شامل لكبار السن وتقييم الحالة العامة',
    icon: '🧓',
    color: 'teal',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'مراقبة ضغط الدم للمسنين',
    price: 500,
    duration: 15,
    category: 'رعاية كبار السن',
    description: 'قياس ومتابعة ضغط الدم لكبار السن بشكل دوري',
    icon: '💓',
    color: 'teal',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'علاج آلام المفاصل',
    price: 1200,
    duration: 20,
    category: 'رعاية كبار السن',
    description: 'علاج آلام المفاصل والتهابات المفاصل المزمنة',
    icon: '🦴',
    color: 'teal',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'متابعة مرضى السكري',
    price: 1000,
    duration: 20,
    category: 'رعاية كبار السن',
    description: 'متابعة مستوى السكر وتعديل جرعات الأنسولين لكبار السن',
    icon: '🍬',
    color: 'teal',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'علاج الدوخة وضعف التوازن',
    price: 900,
    duration: 20,
    category: 'رعاية كبار السن',
    description: 'تقييم وعلاج الدوخة ومشاكل التوازن لدى كبار السن',
    icon: '😵‍💫',
    color: 'teal',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'رعاية قرحة الضغط',
    price: 1500,
    duration: 30,
    category: 'رعاية كبار السن',
    description: 'علاج والاعتناء بقرح الضغط لدى المرضى طريحي الفراش',
    icon: '🛏️',
    color: 'teal',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'مراقبة أدوية كبار السن',
    price: 600,
    duration: 15,
    category: 'رعاية كبار السن',
    description: 'مراجعة أدوية كبار السن وتعديل الجرعات والتفاعلات',
    icon: '💊',
    color: 'teal',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'علاج ضعف الدورة الدموية',
    price: 1200,
    duration: 20,
    category: 'رعاية كبار السن',
    description: 'علاج مشاكل الدورة الدموية الطرفية لدى المسنين',
    icon: '🩸',
    color: 'teal',
    active: true,
    status: 'active',
  },

  // ═══════════════════════════════════════════════════════════
  // 12. متابعة العلاج (Treatment Follow-up) - 8 services
  // ═══════════════════════════════════════════════════════════
  {
    nameAr: 'متابعة الجروح بعد العلاج',
    price: 500,
    duration: 15,
    category: 'متابعة العلاج',
    description: 'فحص الجروح ومتابعة عملية الالتئام وتغيير الضمادات',
    icon: '🩹',
    color: 'indigo',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'متابعة الكسور',
    price: 800,
    duration: 15,
    category: 'متابعة العلاج',
    description: 'فحص الكسور المتجبرة ومتابعة التئام العظم',
    icon: '🦴',
    color: 'indigo',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'متابعة الحروق',
    price: 700,
    duration: 15,
    category: 'متابعة العلاج',
    description: 'متابعة شفاء الحروق وتغيير الضمادات المتخصصة',
    icon: '🔥',
    color: 'indigo',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'متابعة الأمراض المعدية',
    price: 600,
    duration: 15,
    category: 'متابعة العلاج',
    description: 'متابعة حالة المريض بعد الإصابة بالأمراض المعدية',
    icon: '🦠',
    color: 'indigo',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'إعادة تقييم العلاج',
    price: 500,
    duration: 15,
    category: 'متابعة العلاج',
    description: 'إعادة تقييم خطة العلاج وتعديلها حسب استجابة المريض',
    icon: '📋',
    color: 'indigo',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'متابعة نتائج التحاليل',
    price: 400,
    duration: 10,
    category: 'متابعة العلاج',
    description: 'مراجعة نتائج التحاليل المخبرية وشرحها للمريض',
    icon: '📊',
    color: 'indigo',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'متابعة العلاج الطبيعي',
    price: 800,
    duration: 20,
    category: 'متابعة العلاج',
    description: 'متابعة جلسات العلاج الطبيعي وتقييم التحسن',
    icon: '💪',
    color: 'indigo',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'استشارة ما بعد العلاج',
    price: 500,
    duration: 15,
    category: 'متابعة العلاج',
    description: 'استشارة طبية بعد انتهاء العلاج للتأكد من الشفاء الكامل',
    icon: '👨‍⚕️',
    color: 'indigo',
    active: true,
    status: 'active',
  },

  // ═══════════════════════════════════════════════════════════
  // 13. المحاليل الوريدية (IV Fluids) - 10 services
  // ═══════════════════════════════════════════════════════════
  {
    nameAr: 'نورمال سالين (محلول ملحي)',
    price: 1500,
    duration: 45,
    category: 'المحاليل الوريدية',
    description: 'محلول كلوريد الصوديوم 0.9% للترطيب الوريدي وإعادة السوائل',
    icon: '💉',
    color: 'lime',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'دكستروز 5% (جلوكوز)',
    price: 1800,
    duration: 45,
    category: 'المحاليل الوريدية',
    description: 'محلول الجلوكوز 5% للتغذية الوريدية وعلاج انخفاض السكر',
    icon: '💧',
    color: 'lime',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'دكستروز 10%',
    price: 2000,
    duration: 40,
    category: 'المحاليل الوريدية',
    description: 'محلول الجلوكوز المركز للتغذية الوريدية وحالات نقص السكر الشديد',
    icon: '💉',
    color: 'lime',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'رنجر لاكتات',
    price: 2000,
    duration: 45,
    category: 'المحاليل الوريدية',
    description: 'محلول رنجر لاكتات لعلاج الجفاف الشديد والحروق والصدمات',
    icon: '💉',
    color: 'lime',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'محلول رنجر لاكتات دكستروز',
    price: 2200,
    duration: 50,
    category: 'المحاليل الوريدية',
    description: 'مزود رنجر لاكتات مع الجلوكوز للترطيب والتغذية المتزامنة',
    icon: '💧',
    color: 'lime',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'محلول ملحي + دكستروز',
    price: 2000,
    duration: 45,
    category: 'المحاليل الوريدية',
    description: 'تركيب محلول ملحي مع الجلوكوز للمرضى الذين يحتاجون ترطيب وتغذية',
    icon: '💉',
    color: 'lime',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'محلول بوتاسيوم كلورايد',
    price: 2500,
    duration: 60,
    category: 'المحاليل الوريدية',
    description: 'إضافة البوتاسيوم للمحاليل الوريدية لعلاج نقص البوتاسيوم',
    icon: '💉',
    color: 'lime',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'محلول هارتمان',
    price: 2200,
    duration: 45,
    category: 'المحاليل الوريدية',
    description: 'محلول هارتمان للتعويض السريع للسوائل في حالات الصدمة والجفاف',
    icon: '💧',
    color: 'lime',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'محلول صوديوم بيكربونات',
    price: 2800,
    duration: 30,
    category: 'المحاليل الوريدية',
    description: 'محلول بيكربونات الصوديوم لعلاج الحماض الأيضي',
    icon: '💉',
    color: 'lime',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'محلول مغذي مركب',
    price: 3500,
    duration: 90,
    category: 'المحاليل الوريدية',
    description: 'تركيب محلول وريدي مركب يحتوي على أملاح وفيتامينات وجلوكوز',
    icon: '💧',
    color: 'lime',
    active: true,
    status: 'active',
  },

  // ═══════════════════════════════════════════════════════════
  // 14. المضادات الحيوية (Antibiotics) - 10 services
  // ═══════════════════════════════════════════════════════════
  {
    nameAr: 'أموكسيسيلين (كبسولات)',
    price: 800,
    duration: 10,
    category: 'المضادات الحيوية',
    description: 'مضاد حيوي واسع الطيف لعلاج التهابات الجهاز التنفسي والمسالك البولية',
    icon: '💊',
    color: 'fuchsia',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'أموكسيسيلين + كلافولانات',
    price: 1200,
    duration: 10,
    category: 'المضادات الحيوية',
    description: 'أوغمنتين - مضاد حيوي مركب للعدوى البكتيرية المقاومة',
    icon: '💊',
    color: 'fuchsia',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'سيبروفلوكساسين',
    price: 1000,
    duration: 10,
    category: 'المضادات الحيوية',
    description: 'مضاد حيوي للتهابات المسالك البولية والجهاز التنفسي والإسهال البكتيري',
    icon: '💊',
    color: 'fuchsia',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'أزيثرومايسين',
    price: 1500,
    duration: 10,
    category: 'المضادات الحيوية',
    description: 'مضاد حيوي ماكرولايد للتهابات الحلق والرئة والأذن',
    icon: '💊',
    color: 'fuchsia',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'سيفالكسين',
    price: 900,
    duration: 10,
    category: 'المضادات الحيوية',
    description: 'مضاد حيوي سيفالوسبورين للعدوى الجلدية والمسالك البولية',
    icon: '💊',
    color: 'fuchsia',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'ميترونيدازول',
    price: 700,
    duration: 10,
    category: 'المضادات الحيوية',
    description: 'مضاد حيوي للعدوى الطفيلية والبكتيرية اللاهوائية والإسهال',
    icon: '💊',
    color: 'fuchsia',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'سيفراكسون (حقنة)',
    price: 2500,
    duration: 15,
    category: 'المضادات الحيوية',
    description: 'مضاد حيوي وريدي قوي للعدوى الشديدة والالتهابات الخطيرة',
    icon: '💉',
    color: 'fuchsia',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'جنتاميسين (حقنة)',
    price: 1800,
    duration: 15,
    category: 'المضادات الحيوية',
    description: 'مضاد حيوي أمينوغليكوزيد للعدوى البكتيرية الخطيرة',
    icon: '💉',
    color: 'fuchsia',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'دوكسيسايكلين',
    price: 800,
    duration: 10,
    category: 'المضادات الحيوية',
    description: 'مضاد حيوي تتراسيكلين للملاريا والأمراض المنقولة جنسياً والتهابات الجلد',
    icon: '💊',
    color: 'fuchsia',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'كوتريموكسازول',
    price: 600,
    duration: 10,
    category: 'المضادات الحيوية',
    description: 'مضاد حيوي واسع الطيف للتهابات المسالك البولية والإسهال والتهاب الأذن',
    icon: '💊',
    color: 'fuchsia',
    active: true,
    status: 'active',
  },

  // ═══════════════════════════════════════════════════════════
  // 15. المهدئات والألم (Sedatives & Pain Relief) - 10 services
  // ═══════════════════════════════════════════════════════════
  {
    nameAr: 'باراسيتامول (أقراص)',
    price: 300,
    duration: 5,
    category: 'المهدئات والألم',
    description: 'مسكن للآلام الخفيفة والمتوسطة وخافض للحرارة',
    icon: '😴',
    color: 'slate',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'إيبوبروفين',
    price: 500,
    duration: 5,
    category: 'المهدئات والألم',
    description: 'مضاد التهاب غير ستيرويدي مسكن للآلام والالتهابات',
    icon: '😴',
    color: 'slate',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'ديكلوفيناك',
    price: 600,
    duration: 5,
    category: 'المهدئات والألم',
    description: 'مسكن قوي مضاد للالتهاب لآلام المفاصل والعضلات',
    icon: '😴',
    color: 'slate',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'ترامادول',
    price: 1500,
    duration: 10,
    category: 'المهدئات والألم',
    description: 'مسكن أفيوني للآلام الشديدة - يتطلب وصفة طبية',
    icon: '😴',
    color: 'slate',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'ديازيبام (فاليوم)',
    price: 1200,
    duration: 10,
    category: 'المهدئات والألم',
    description: 'مهدئ للقلق والتشنجات العضلية واضطرابات النوم',
    icon: '😴',
    color: 'slate',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'حقنة مسكنة وريدية',
    price: 2000,
    duration: 15,
    category: 'المهدئات والألم',
    description: 'حقنة مسكنة وريدية سريعة المفعول للآلام الحادة',
    icon: '💉',
    color: 'slate',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'كورتيزون (بريدنيزولون)',
    price: 1800,
    duration: 10,
    category: 'المهدئات والألم',
    description: 'كورتيكوستيرويد للالتهابات الشديدة والحساسية والأزمات',
    icon: '💊',
    color: 'slate',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'حقنة كورتيزون موضعية',
    price: 2200,
    duration: 15,
    category: 'المهدئات والألم',
    description: 'حقنة كورتيزون موضعية لآلام المفاصل والالتهابات الموضعية',
    icon: '💉',
    color: 'slate',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'مورفين (حقنة)',
    price: 3000,
    duration: 15,
    category: 'المهدئات والألم',
    description: 'مسكن أفيوني قوي جداً للآلام الشديدة والحرجة - وصفة طبية خاصة',
    icon: '💉',
    color: 'slate',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'أمبيبيرازين (مضاد تشنج)',
    price: 1000,
    duration: 10,
    category: 'المهدئات والألم',
    description: 'مضاد للتشنجات والقلق واضطرابات الجهاز العصبي',
    icon: '💊',
    color: 'slate',
    active: true,
    status: 'active',
  },

  // ═══════════════════════════════════════════════════════════
  // 16. الفيتامينات والمكملات (Vitamins & Supplements) - 10 services
  // ═══════════════════════════════════════════════════════════
  {
    nameAr: 'فيتامين د (كبسولات)',
    price: 800,
    duration: 5,
    category: 'الفيتامينات والمكملات',
    description: 'كبسولات فيتامين د3 لعلاج النقص وتقوية العظام',
    icon: '☀️',
    color: 'yellow',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'فيتامين سي',
    price: 500,
    duration: 5,
    category: 'الفيتامينات والمكملات',
    description: 'فيتامين سي لتعزيز المناعة ومقاومة العدوى وتسريع الشفاء',
    icon: '🍊',
    color: 'yellow',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'فيتامين ب المركب',
    price: 700,
    duration: 5,
    category: 'الفيتامينات والمكملات',
    description: 'مركب فيتامينات ب لتقوية الأعصاب والطاقة والدم',
    icon: '💊',
    color: 'yellow',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'حقنة فيتامين د',
    price: 2000,
    duration: 10,
    category: 'الفيتامينات والمكملات',
    description: 'حقنة فيتامين د عضلية للنقص الحاد - جرعة عالية سريعة الامتصاص',
    icon: '💉',
    color: 'yellow',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'حقنة فيتامين ب12',
    price: 1800,
    duration: 10,
    category: 'الفيتامينات والمكملات',
    description: 'حقنة فيتامين ب12 عضلية لعلاج فقر الدم وضعف الأعصاب',
    icon: '💉',
    color: 'yellow',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'حديد + حمض الفوليك',
    price: 600,
    duration: 5,
    category: 'الفيتامينات والمكملات',
    description: 'مكمل الحديد وحمض الفوليك لعلاج فقر الدم الغذائي',
    icon: '🩸',
    color: 'yellow',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'كالسيوم + فيتامين د',
    price: 900,
    duration: 5,
    category: 'الفيتامينات والمكملات',
    description: 'مكمل الكالسيوم مع فيتامين د لتقوية العظام والأسنان',
    icon: '🦴',
    color: 'yellow',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'أوميغا 3 (زيت السمك)',
    price: 1200,
    duration: 5,
    category: 'الفيتامينات والمكملات',
    description: 'كبسولات أوميغا 3 لصحة القلب والأوعية الدموية والدماغ',
    icon: '🐟',
    color: 'yellow',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'زنك + فيتامين سي',
    price: 700,
    duration: 5,
    category: 'الفيتامينات والمكملات',
    description: 'مكمل الزنك مع فيتامين سي لتعزيز المناعة وتسريع الشفاء',
    icon: '🌟',
    color: 'yellow',
    active: true,
    status: 'active',
  },
  {
    nameAr: 'مكمل غذائي متكامل',
    price: 1500,
    duration: 5,
    category: 'الفيتامينات والمكملات',
    description: 'مكمل غذائي شامل بالفيتامينات والمعادن للصحة العامة',
    icon: '💊',
    color: 'yellow',
    active: true,
    status: 'active',
  },
];
